name: hbologger
description: "A Flutter package for implementing the Chain of Responsibility pattern with error logging using Riverpod and Dio."
version: 0.0.4
homepage: "https://pub.dev/packages/hbologger"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
